### ISSUE TITLE
ZBXNEXT-4640

### ISSUE THREAD

**Issue by zhiyuazo** [zabbix/zabbix-patches#16]
hi , 
we complete a new feature and now need review by zabbix official . 
The initial request: https://www.zabbix.com/forum/zabbix-help/52013-zabbix-has-plan-to-integrate-keycloak-as-sso     
i also create a JIRA ticket: https://support.zabbix.com/browse/ZBXNEXT-4640  

I want to post our patch to reviewed by you, is right below procedure?

1.  Clone this repo
2.  Create a directory in **zabbix-patches/zabbix-3.0/ZBXNEXT-4640**
3.  Put our diff information into this directory 
4.  git push to zabbix-patch  

is Right for 1 , 2 , 3 ,4 ?

I also wan to know, what's difference between **zabbix-patch repo** and https://share.zabbix.com/ ?

**Comment by paskal** [comment]
Thanks for asking! It's a bit more complex, grep for "ZBXNEXT-1510" to see an example of all places where the patch should be mentioned in order to be used. Generally just diff is OK, if you'll miss something I'll fix it after merge.
Also point 5 should be to send a pull request.

**Comment by zhiyuazo** [comment]
hi, paskal, 
Thank your timely response. 
1. The 1  2  3 4  procedure is right ? 
2. what's difference between zabbix-patch repo and https://share.zabbix.com/ ?

**Comment by paskal** [comment]
1) It is.
2) This is community-driven tool only for patches and targeted at applying them as easy as it could be. 
share.zabbix.com have all kind of stuff but not targeted at anything particular from my POV.
Generally I think what including a patch there might be enough for giving it for review to Zabbix SIA, and separately you might want to add it to share.zabbix.com for more wide community use.
Someone just looking for a auth provider you've implemented will google for it and find ZBXNEXT-4640 Jira ticket and link to this place, and someone just wandering on share.zabbix.com might see it in some listing and try it out just out of curiosity - I think that's how it works, it's up to you where to list your work.

**Comment by zhiyuazo** [comment]
hi, paskal:
very thank your detailed explanation. 
i will work on this place.

**Comment by CsatariGergely** [comment]
@paskal If my understanding is correct your description is about keeping the change sitting here and let people patching it for themselves while plan would be to get this into "upstream" Zabbix.

**Comment by paskal** [comment]
That's general plan for most of the patches we have there. I'm constantly talking with Zabbix developers about patches inclusion into mainstream Zabbix, it was already done for some of them and it's in progress for others.
Only current problem I can't solve myself is absent [ZBXNEXT-1810](https://support.zabbix.com/browse/ZBXNEXT-1810) patch for 3.4 - it [was ready](https://github.com/zabbix/zabbix-patches/blob/96dc7d42a3c12693e77c00b1d5561310caec70da/zabbix-3.4/ZBXNEXT-1810-1/ZBXNEXT-1810-1.patch) but something was slightly wrong with it, I guess I'll create separate issue here with label "need help" for fixing it.

**Comment by CsatariGergely** [comment]
The advice what I've got in #zabbix on freenode is that we should create a patch into this repo and a Jira ticket to https://support.zabbix.com and Zabbix developers will check if they can merge our code. Soo @zhiyuazo created the Jira issue ([ZBXNEXT-4640](https://support.zabbix.com/browse/ZBXNEXT-4640)) and the patch is on its way. Is there anything more what we can do?

**Comment by paskal** [comment]
I suggest following workflow in general:
1. Create Jira ticket with feature request
2. Create a patch for it
3. Post it there
4. Write to ticket what you have a patch there and you want it to be merged to upstream Zabbix
5. Make sure someone from Zabbix read it by asking in #zabbix channel on Freenode.
You couldn't do much more than these 5 points, I know someone in Zabbix company who I work with on these patches inclusion and I'll make sure he know what there is new patch worth it.

**Comment by CsatariGergely** [comment]
Thanks @paskal for the advices.

**Comment by paskal** [comment]
Patch is added, resolving this issue.
