### ISSUE TITLE
Upgrade zabbix

### ISSUE THREAD

**Issue by Tehniels2000** [zabbix/zabbix-patches#22]
I upgraded my zabbix version but now it shows this error when i go to the dashboard.

The Zabbix database version does not match current requirements. Your database version: 5040000. Required version: 5000000. 
Please contact your system administrator.

**Comment by paskal** [comment]
You are running Zabbix Server or Zabbix Web UI of the wrong version, 5.0 instead of 5.4. Please upgrade both to resolve this error.
